export { default as BootScene } from './Boot'
export { default as BattleScene } from './Battle'
export { default as MenuScene } from './Menu'
export { default as MapScene } from './Map'
export { default as DiceScene } from './Dice'
export { default as HudScene } from './Hud'
export { default as WinScene } from './Win'
