export { default as BootScene } from './Boot'
export { default as GameScene } from './Game'
export { default as MenuScene } from './Menu'
export { default as MapScene } from './Map'
export { default as HudScene } from './Hud'
export { default as WinScene } from './Win'
